package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"main/graph/model"
)

// UserInfoByName is the resolver for the userInfoByName field.
func (r *queryResolver) UserInfoByName(ctx context.Context, name string) (model.UserInfo, error) {
	return &model.User{ID: name}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
